beyourmarket-master/beyourmarket-master/src/BeYourMarket.Web/Areas/Admin/Controllers/ListingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using BeYourMarket.Service;
using System.Threading.Tasks;
using BeYourMarket.Model.Models;
using Repository.Pattern.UnitOfWork;
using Newtonsoft.Json;
using BeYourMarket.Web.Extensions;
using BeYourMarket.Web.Models.Grids;
using BeYourMarket.Web.Models;
using BeYourMarket.Web.Utilities;
using ImageProcessor.Imaging.Formats;
using System.Drawing;
using ImageProcessor;
using System.IO;
using System.Text;
using BeYourMarket.Model.Enum;
using RestSharp;
using BeYourMarket.Web.Areas.Admin.Models;
using Postal;
using System.Net.Mail;
using System.Net;
using BeYourMarket.Service.Models;
using BeYourMarket.Core.Web;

namespace BeYourMarket.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ListingController : Controller
    {
        #region Fields
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;

        private readonly ISettingService _settingService;
        private readonly ISettingDictionaryService _settingDictionaryService;

        private readonly ICategoryService _categoryService;
        private readonly ICategoryListingTypeService _categoryListingTypeService;

        private readonly IListingService _listingService;
        private readonly IListingTypeService _listingTypeService;
        private readonly IListingReviewService _listingReviewService;

        private readonly ICustomFieldService _customFieldService;
        private readonly ICustomFieldCategoryService _customFieldCategoryService;
        private readonly ICustomFieldListingService _customFieldListingService;

        private readonly IContentPageService _contentPageService;

        private readonly IOrderService _orderService;

        private readonly IListingPictureService _listingPictureservice;
        private readonly IPictureService _pictureService;

        private readonly IEmailTemplateService _emailTemplateService;

        private readonly DataCacheService _dataCacheService;
        private readonly SqlDbService _sqlDbService;

        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        #endregion

        #region Properties
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        #endregion

        #region Constructor
        public ListingController(
            IUnitOfWorkAsync unitOfWorkAsync,
            ISettingService settingService,
            ICategoryService categoryService,
            ICategoryListingTypeService categoryListingTypeService,
            IListingService listingService,
            IListingTypeService listingTypeService,
            ICustomFieldService customFieldService,
            ICustomFieldCategoryService customFieldCategoryService,
            ICustomFieldListingService customFieldListingService,
            IContentPageService contentPageService,
            IOrderService orderService,
            ISettingDictionaryService settingDictionaryService,
            IEmailTemplateService emailTemplateService,
            IPictureService pictureService,
            IListingPictureService listingPictureservice,
            IListingReviewService listingReviewService,
            DataCacheService dataCacheService,
            SqlDbService sqlDbService)
        {
            _settingService = settingService;
            _settingDictionaryService = settingDictionaryService;

            _categoryService = categoryService;
            _categoryListingTypeService = categoryListingTypeService;

            _listingService = listingService;
            _listingTypeService = listingTypeService;

            _pictureService = pictureService;
            
            _listingPictureservice = listingPictureservice;
            _listingReviewService = listingReviewService;

            _customFieldService = customFieldService;
            _customFieldCategoryService = customFieldCategoryService;
            _customFieldListingService = customFieldListingService;

            _orderService = orderService;

            _emailTemplateService = emailTemplateService;
            _contentPageService = contentPageService;
            _unitOfWorkAsync = unitOfWorkAsync;
            _dataCacheService = dataCacheService;
            _sqlDbService = sqlDbService;
        }
        #endregion

        #region Methods
        public ActionResult Categories()
        {
            var categories = _categoryService.Queryable().OrderBy(x => x.Parent).ThenBy(x => x.Ordering).ToList().GenerateTree(x => x.ID, x => x.Parent);

            return View(categories);
        }


        public class CategoryJson
        {
            public int id { get; set; }

            public CategoryJson[] children { get; set; }
        }

        [HttpPost]
        public async Task<ActionResult> CategoriesUpdate(string JsonCategories)
        {
            var result = JsonConvert.DeserializeObject<CategoryJson[]>(JsonCategories);

            await SetCategoryOrdering(0, result);

            await _unitOfWorkAsync.SaveChangesAsync();

            _dataCacheService.RemoveCachedItem(CacheKeys.ListingTypes);
            _dataCacheService.RemoveCachedItem(CacheKeys.Categories);

            return RedirectToAction("Categories");
        }

        /// <summary>
        /// Recursive method to set category ordering
        /// </summary>
        /// <param name="json"></param>
        public async Task SetCategoryOrdering(int parent, CategoryJson[] json)
        {
            int sortOrder = 0;
            foreach (var item in json)
            {
                var category = await _categoryService.FindAsync(item.id);
                category.Parent = parent;
                category.Ordering = sortOrder;
                category.ObjectState = Repository.Pattern.Infrastructure.ObjectState.Modified;

                _categoryService.Update(category);

                sortOrder++;

                if (item.children != null)
                {
                    await SetCategoryOrdering(item.id, item.children);
                }
            }
        }

        public async Task<ActionResult> CategoryUpdate(int? id)
        {
            Category category;

            var categoryModel = new CategoryModel();

            var ListingTypes = await _listingTypeService.Query().SelectAsync();
            categoryModel.ListingTypes = ListingTypes.ToList();

            if (id.HasValue)
            {
                category = await _categoryService.FindAsync(id);
                var categoryListingTypes = await _categoryListingTypeService.Query(x => x.CategoryID == id.Value).SelectAsync();
                categoryModel.CategoryListingTypeID = categoryListingTypes.Select(x => x.ListingTypeID).ToList();
            }
            else
                category = new Category() { Enabled = true };

            categoryModel.Category = category;

            return View(categoryModel);
        }

        [HttpPost]
        public async Task<ActionResult> CategoryUpdate(CategoryModel model)
        {
            if (model.Category.ID == 0)
            {
                model.Category.ObjectState = Repository.Pattern.Infrastructure.ObjectState.Added;
                model.Category.Parent = 0;

                _categoryService.Insert(model.Category);
            }
            else
            {
                var categoryExisting = await _categoryService.FindAsync(model.Category.ID);

                categoryExisting.Name = model.Category.Name;
                categoryExisting.Description = model.Category.Description;
                categoryExisting.Enabled = model.Category.Enabled;

                categoryExisting.ObjectState = Repository.Pattern.Infrastructure.ObjectState.Modified;

                _categoryService.Update(categoryExisting);
            }

            await _unitOfWorkAsync.SaveChangesAsync();

            // Delete existing category item types
            var ListingTypes = _categoryListingTypeService.Queryable().Where(x => x.CategoryID == model.Category.ID).Select(x => x.ID).ToList();
            foreach (var ListingTypeID in ListingTypes)
            {
                await _categoryListingTypeService.DeleteAsync(ListingTypeID);
            }

            // Insert category item types
            foreach (var categoryListingTypeID in model.CategoryListingTypeID)
            {
                _categoryListingTypeService.Insert(new CategoryListingType()
                {
                    CategoryID = model.Category.ID,
                    ListingTypeID = categoryListingTypeID,
                    ObjectState = Repository.Pattern.Infrastructure.ObjectState.Added
                });
            }

            await _unitOfWorkAsync.SaveChangesAsync();

            _dataCacheService.RemoveCachedItem(CacheKeys.ListingTypes);
            _dataCacheService.RemoveCachedItem(CacheKeys.Categories);

beyourmarket-master/beyourmarket-master/src/BeYourMarket.Web/Areas/Admin/Views/Shared/_CategoryCustomFields.cshtml
@model BeYourMarket.Web.Models.CustomFieldListingModel

@if (Model.MetaCategories.Count > 0)
{
    <fieldset>
        <legend>[[[Custom Fields]]]</legend>

        @foreach (var metaCategory in Model.MetaCategories)
        {
            var field = metaCategory.MetaField;
            var controlType = (BeYourMarket.Model.Enum.Enum_MetaFieldControlType)field.ControlTypeID;
            var options = new string[] { };
            if (!string.IsNullOrEmpty(field.Options))
            {
                options = field.Options.Split(new char[] { ',' });
            }

            var itemMeta = field.ListingMetas.Where(x => x.ListingID == Model.ListingID).FirstOrDefault();
            var itemValue = string.Empty;
            if (itemMeta != null)
            {
                itemValue = itemMeta.Value;
            }

            string controlId = string.Format("customfield_{0}_{1}_{2}", metaCategory.ID, metaCategory.CategoryID, metaCategory.FieldID);

            switch (controlType)
            {
                case BeYourMarket.Model.Enum.Enum_MetaFieldControlType.None:
                    break;
                case BeYourMarket.Model.Enum.Enum_MetaFieldControlType.DropdownList:
                    <div class="form-group">
                        <label class="col-md-2 control-label">@field.Name</label>
                        <div class="col-md-10">
                            <select class="form-control" name="@controlId" id="@controlId" data-placeholder="@field.Placeholder" @(field.Required ? "required" : "")>
                                @foreach (var option in options)
                                {
                                    <option value="@option" @(itemValue == option ? "selected" : "")>@option</option>
                                }
                            </select>
                        </div>
                    </div>
                                break;
                case BeYourMarket.Model.Enum.Enum_MetaFieldControlType.RadioList:
                <div class="form-group">
                    <label class="col-md-2 control-label">@field.Name</label>
                    <div class="col-md-10">
                        @foreach (var option in options)
                        {
                            <input type="radio" id="@controlId" name="@controlId" value="@option" @(itemValue == option ? "checked" : "") @(field.Required ? "required" : "") /><label for="@controlId">@option</label>
                        }
                    </div>
                </div>
                        break;
                case BeYourMarket.Model.Enum.Enum_MetaFieldControlType.Checkboxes:
                <div class="form-group">
                    <label class="col-md-2 control-label">@field.Name</label>
                    <div class="col-md-10">
                        @foreach (var option in options)
                        {
                            <input type="checkbox" id="@controlId" name="@controlId" value="@option" @(itemValue == option ? "checked" : "") @(field.Required ? "required" : "") /><label for="@controlId">@option</label>
                        }
                    </div>
                </div>
                        break;
                case BeYourMarket.Model.Enum.Enum_MetaFieldControlType.TextBox:
                <div class="form-group">
                    <label class="col-md-2 control-label">@field.Name</label>
                    <div class="col-md-10">
                        <input type="text" id="@controlId" name="@controlId" class="form-control input-lg" placeholder="@field.Placeholder" value="@itemValue" @(field.Required ? "required" : "")>
                    </div>
                </div>
                        break;
                case BeYourMarket.Model.Enum.Enum_MetaFieldControlType.MultilineTextbox:
                <div class="form-group">
                    <label class="col-md-2 control-label">@field.Name</label>
                    <div class="col-md-10">
                        <textarea class="form-control input-lg" rows="4" placeholder="@field.Placeholder" id="@controlId" name="@controlId" @(field.Required ? "required" : "")>@itemValue</textarea>
                    </div>
                </div>
                        break;
                case BeYourMarket.Model.Enum.Enum_MetaFieldControlType.Datepicker:
                        break;
                default:
                        break;
            }
        }
    </fieldset>
}

beyourmarket-master/beyourmarket-master/src/BeYourMarket.Web/Areas/Admin/Views/Shared/_LanguageSelector.cshtml
@using i18n;
@model BeYourMarket.Web.Models.LanguageSelectorModel

@if (Model.LanguageList.Count > 0)
{
    <li class="dropdown">
        <a data-toggle="dropdown" class="dropdown-toggle" href="#">@Model.DisplayName <span class="caret"></span></a>
        <ul role="menu" class="dropdown-menu fadeInUp animated">
            @foreach (var item in Model.LanguageList)
            {
                <li>
                    <a href="@Url.Action("SetLanguage", "Manage", new { langtag = item.Culture, returnUrl = Request.Url.PathAndQuery })">@item.DisplayName</a>
                </li>
            }
        </ul>
    </li>
}

beyourmarket-master/beyourmarket-master/src/BeYourMarket.Web/Areas/Admin/Views/Shared/_Layout.cshtml
@using Microsoft.Practices.Unity;
@using Microsoft.Practices.Unity.Configuration;

@{
    var settings = CacheHelper.Settings;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpeg" href="@ImageHelper.GetCommunityImagePath("favicon")" />

    <title>@ViewBag.Title - @CacheHelper.Settings.Name</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- Bootstrap core CSS -->
    <link href="~/css/admin/bootstrap-reset.css" rel="stylesheet">

    <!--Animation css-->
    <link href="~/css/animate.css" rel="stylesheet" />
    <link href="~/js/ripples/css/ripples.min.css" rel="stylesheet" />

    <!--Icon-fonts css-->
    <link href="~/css/font-awesome/css/font-awesome.css" rel="stylesheet" />        

    <!-- Custom styles for this template -->
    <link href="~/css/admin/style.css" rel="stylesheet" />    
    <link href="~/css/admin/style-responsive.css" rel="stylesheet" />    

    @RenderSection("styles", required: false)
</head>
<body>
    <aside class="left-panel">

        <div class="logo">
            <a href="@Url.Action("Index", "Manage")" class="logo-expanded">
                @*<img src="@ImageHelper.GetCommunityImagePath("logo", "png")" alt="logo">*@
                <span class="nav-label">@settings.Name</span>
            </a>
        </div>

        @Html.Partial("_NavigationSide")

        <footer class="footer">
            <a href="http://beyourmarket.com">&copy; @DateTime.Now.Year - BeYourMarket.com</a>
        </footer>

    </aside>
    <section class="content">
        @Html.Partial("_NavigationTop")

        @RenderBody()
    </section>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script src="~/js/sweet-alert/sweetalert.min.js"></script>
    <script src="~/js/ripples/js/ripples.min.js"></script>
    <script src="~/js/ripples/js/ripples.init.js"></script>    
    <script src="~/js/nicescroll/jquery.nicescroll.min.js"></script>

    <script src="~/js/admin/app.js"></script>
</body>
</html>

beyourmarket-master/beyourmarket-master/src/BeYourMarket.Web/Areas/Admin/Views/Shared/_LayoutNoSide.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/jpeg" href="@ImageHelper.GetCommunityImagePath("favicon")" />

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")

    <!-- Bootstrap core CSS -->
    <link href="~/css/admin/bootstrap-reset.css" rel="stylesheet">

    <!--Animation css-->
    <link href="~/css/animate.css" rel="stylesheet" />

    <!--Icon-fonts css-->
    <link href="~/css/font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css/admin/style.css" rel="stylesheet" />    
    <link href="~/css/admin/style-responsive.css" rel="stylesheet" />    

    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BeYourMarket</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

beyourmarket-master/beyourmarket-master/src/BeYourMarket.Web/Areas/Admin/Views/Shared/_ListingTypes.cshtml
@model BeYourMarket.Web.Models.ListingUpdateModel

<!-- Show Listing Type -->
<div class="form-group">
    <label class="col-md-2 control-label">[[[Listing Type]]]</label>
    <div class="col-md-10">
        @Html.DropDownListFor(m => m.ListingTypeID, new SelectList(Model.ListingTypes, "ID", "Name", Model.ListingItem.ListingTypeID), new { @class = "form-control input-lg" })        
    </div>
</div>  

beyourmarket-master/beyourmarket-master/src/BeYourMarket.Web/Areas/Admin/Views/Shared/_NavigationSide.cshtml
<!-- Navbar Start -->
@helper DisplayAttribute(string menu)
{
    var attribute = ViewContext.RouteData.Values["action"].ToString().ToLowerInvariant() == menu ? "active" : null;

    @attribute
}

@helper DisplayGroupAttribute(string menu)
{
    var groupDashboard = new string[] {
            "dashboard",
            "index"
        };

    var groupSettings = new string[] {
            "settings",
            "settingsemail",
            "emailtemplates",
            "settingslanguage",
        };

    var groupUsers = new string[] {
            "users"
        };

    var groupListings = new string[] {
            "listings",
            "listingupdate",
            "listingtypes",
            "categories",
            "categoryupdate",
            "customfields",
            "customfieldupdate"
        };

    var groupDesign = new string[] {
            "appearance",
            "codestyle",
            "codescript"            
        };

    var groupPages = new string[] {
            "contentpages",
            "contentpageupdate"
        };

    var groupPayments = new string[] {
            "paymentsetting",
            "order",
            "transaction"
        };

    var groupPlugins = new string[] {
            "plugins"
        };

    var groupDictionary = new Dictionary<string, string[]>();
    groupDictionary.Add("dashboard", groupDashboard);
    groupDictionary.Add("settings", groupSettings);
    groupDictionary.Add("users", groupUsers);
    groupDictionary.Add("listings", groupListings);
    groupDictionary.Add("design", groupDesign);
    groupDictionary.Add("contentpages", groupPages);
    groupDictionary.Add("payments", groupPayments);
    groupDictionary.Add("plugins", groupPlugins);

    var attribute = groupDictionary[menu].Contains(ViewContext.RouteData.Values["action"].ToString().ToLowerInvariant()) ? "active" : null;

    @attribute
}

<nav class="navigation">
    <ul class="list-unstyled">
        <li class="has-submenu @DisplayGroupAttribute("dashboard")">
            <a href="@Url.Action("Index", "Manage")"><i class="fa fa-home"></i> <span class="nav-label">[[[Dashboard]]]</span></a>
        </li>

        <li class="has-submenu @DisplayGroupAttribute("listings")">
            <a href="#"><i class="fa fa-th-list"></i> <span class="nav-label">[[[Listings]]]</span></a>
            <ul class="list-unstyled">
                <li class="@DisplayAttribute("categories")"><a href="@Url.Action("Categories", "Listing")">[[[Manage Categories]]]</a></li>
                <li class="@DisplayAttribute("listingtypes")"><a href="@Url.Action("ListingTypes", "Listing")">[[[Manage Listing Types]]]</a></li>
                <li class="@DisplayAttribute("listings")"><a href="@Url.Action("Listings", "Listing")">[[[Manage Listings]]]</a></li>
                <li class="@DisplayAttribute("customfields")"><a href="@Url.Action("CustomFields", "Listing")">[[[Custom Fields]]]</a></li>
            </ul>
        </li>

        <li class="has-submenu @DisplayGroupAttribute("design")">
            <a href="#"><i class="fa fa-paint-brush"></i> <span class="nav-label">[[[Design]]]</span></a>
            <ul class="list-unstyled">
                <li class="@DisplayAttribute("appearance")"><a href="@Url.Action("Appearance", "Design")">[[[Appearance]]]</a></li>
                <li class="@DisplayAttribute("codestyle")"><a href="@Url.Action("CodeStyle", "Design")">[[[Custom CSS]]]</a></li>
                <li class="@DisplayAttribute("codescript")"><a href="@Url.Action("CodeScript", "Design")">[[[Custom Javascript]]]</a></li>
            </ul>
        </li>

        <li class="has-submenu @DisplayGroupAttribute("settings")">
            <a href="#"><i class="fa fa-gears"></i> <span class="nav-label">[[[Settings]]]</span></a>
            <ul class="list-unstyled">
                <li class="@DisplayAttribute("settings")">
                    <a href="@Url.Action("Settings", "Manage")">[[[General Settings]]]</a>
                </li>
                <li class="@DisplayAttribute("settingsemail")">
                    <a href="@Url.Action("SettingsEmail", "Manage")">[[[Email Settings]]]</a>
                </li>
                <li class="@DisplayAttribute("emailtemplates")">
                    <a href="@Url.Action("EmailTemplates", "Manage")">[[[Email Templates]]]</a>
                </li>
                <li class="@DisplayAttribute("settingslanguage")">
                    <a href="@Url.Action("SettingsLanguage", "Manage")">[[[Language Settings]]]</a>
                </li>
            </ul>
        </li>

        <li class="has-submenu @DisplayGroupAttribute("payments")">
            <a href="#"><i class="fa fa-dollar"></i> <span class="nav-label">[[[Payments]]]</span></a>
            <ul class="list-unstyled">
                <li class="@DisplayAttribute("order")">
                    <a href="@Url.Action("Order", "Payment")">[[[Orders]]]</a>
                </li>
                <li class="@DisplayAttribute("transaction")">
                    <a href="@Url.Action("Transaction", "Payment")">[[[Transactions]]]</a>
                </li>
                <li class="@DisplayAttribute("paymentsetting")">
                    <a href="@Url.Action("PaymentSetting", "Payment")">[[[Payment Settings]]]</a>
                </li>
            </ul>
        </li>

        <li class="has-submenu @DisplayGroupAttribute("users")">
            <a href="@Url.Action("Users", "Manage", new { area = "Admin" })"><i class="fa fa-user"></i> <span class="nav-label">[[[Manage Users]]]</span></a>            
        </li>

        <li class="has-submenu @DisplayGroupAttribute("contentpages")">
            <a href="#"><i class="fa fa-file"></i> <span class="nav-label">[[[Pages]]]</span></a>
            <ul class="list-unstyled">
                <li class="@DisplayAttribute("contentpageupdate")">
                    <a href="@Url.Action("ContentPageUpdate", "ContentPage", new { area = "Admin", id = "" })">[[[Add new page]]]</a>
                </li>
                <li class="@DisplayAttribute("contentpages")">
                    <a href="@Url.Action("ContentPages", "ContentPage", new { area = "Admin" })">[[[Manage Pages]]]</a>
                </li>
            </ul>
        </li>

        <li class="has-submenu @DisplayGroupAttribute("plugins")">
            <a href="#"><i class="fa fa-plug"></i> <span class="nav-label">[[[Plugins]]]</span></a>
            <ul class="list-unstyled">
                <li class="@DisplayAttribute("plugins")">
                    <a href="@Url.Action("Plugins", "Plugin", new { area = "Admin", id = "" })">[[[Manage Plugins]]]</a>
                </li>                
            </ul>
        </li>

        <li class="has-submenu">
            <a href="https://beyourmarket.atlassian.net" target="_blank"><i class="fa fa-question"></i> <span class="nav-label">[[[Guide]]]</span></a>
        </li>
    </ul>
</nav>

beyourmarket-master/beyourmarket-master/src/BeYourMarket.Web/Areas/Admin/Views/Shared/_NavigationTop.cshtml
@using Microsoft.AspNet.Identity
<header class="top-head container-fluid">
    <button type="button" class="navbar-toggle pull-left">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

    <nav class=" navbar-default hidden-xs" role="navigation">
        <ul class="nav navbar-nav">

            <li><a href="@Url.Action("Index", "Home", new { area = string.Empty })" target="_blank">[[[Frontend]]]</a></li>

            @Html.Action("LanguageSelector", "Manage", new { area = "Admin" })
        </ul>
    </nav>

    @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
    {
        @Html.AntiForgeryToken()
        <ul class="list-inline navbar-right top-menu top-right-menu">
            <li class="dropdown text-center">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <img alt="" src="@BeYourMarket.Web.Utilities.ImageHelper.GetUserProfileImagePath(User.Identity.GetUserId())" class="img-circle profile-img thumb-sm">
                    <span class="username">@User.Identity.User().FullName </span> <span class="caret"></span>
                </a>
                <ul class="dropdown-menu extended pro-menu fadeInUp animated" tabindex="5003" style="overflow: hidden; outline: none;">
                    <li><a href="@Url.Action("Index", "Home", new { area = "" })"><i class="fa fa-globe"></i> [[[Frontend]]]</a></li>
                    <li><a href="javascript:document.getElementById('logoutForm').submit()"><i class="fa fa-sign-out"></i> [[[Log off]]]</a></li>
                </ul>
            </li>
        </ul>
    }
</header>