cocorico-master/cocorico-master/src/Cocorico/CMSBundle/Entity/Footer.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cocorico\CMSBundle\Entity;

use Cocorico\CMSBundle\Model\BaseFooter;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;


/**
 * Footer
 *
 * @ORM\Entity(repositoryClass="Cocorico\CMSBundle\Repository\FooterRepository")
 *
 * @ORM\Table(name="footer",indexes={
 *    @ORM\Index(name="footer_published_idx", columns={"published"}),
 *  })
 *
 */
class Footer extends BaseFooter
{
    use ORMBehaviors\Timestampable\Timestampable;
    use ORMBehaviors\Translatable\Translatable;

    /**
     * @ORM\Column(name="id", type="bigint", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     *
     * @var integer
     */
    private $id;

    public function __construct()
    {
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        return (string)$this->translate()->getTitle();
    }

    public function getLink()
    {
        return (string)$this->translate()->getLink();
    }

    public function getUrl()
    {
        return (string)$this->translate()->getUrl();
    }

    public function __toString()
    {
        return $this->getTitle();
    }
}

cocorico-master/cocorico-master/src/Cocorico/CMSBundle/Entity/FooterTranslation.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cocorico\CMSBundle\Entity;

use Cocorico\CMSBundle\Model\BaseFooterTranslation;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * @ORM\Entity
 *
 * @ORM\Table(name="footer_translation",indexes={
 *    @ORM\Index(name="footer_url_hash_idx", columns={"url_hash"})
 *  })
 *
 */
class FooterTranslation extends BaseFooterTranslation
{
    use ORMBehaviors\Translatable\Translation;

}

cocorico-master/cocorico-master/src/Cocorico/CMSBundle/Controller/Frontend/FooterController.php
<?php

/*
 * This file is part of the Cocorico package.
 *
 * (c) Cocolabs SAS <contact@cocolabs.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cocorico\CMSBundle\Controller\Frontend;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Footer frontend controller.
 *
 * @Route("/footer")
 */
class FooterController extends Controller
{
    /**
     * Display footer links
     *
     * @param  Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(Request $request)
    {
        $footers = $this->get('cocorico_cms.footer.manager')->findByURL(
            $request->getUri(),
            $request->getLocale()
        );

        return $this->render(
            '@CocoricoCMS/Frontend/Footer/index.html.twig',
            array(
                'footers' => $footers
            )
        );

    }
}

cocorico-master/cocorico-master/src/Cocorico/CMSBundle/Resources/views/Frontend/Footer/index.html.twig
{% if footers|length %}
    <aside class="aside-footer">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <nav class="navarea">
                        <ul class="list-unstyled pull-left">
                            <li class="title">{{ 'footer.title.various'|trans({}, 'cocorico') }}</li>
                            {% for footer in footers %}
                                <li>
                                    <a href="{{ footer.link }}">{{ footer.title }}</a>
                                </li>
                                {% if loop.index is divisible by(3) and not loop.last %}
                                    {{ '</ul>' }}
                                    {{ '<ul class="list-unstyled pull-left">' }}
                                    {{ '<li class="title">&nbsp;</li>' }}
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </aside>
{% endif %}